[tool.flakehell]
format = "colored"
max_line_length = 79
exclude = [
  # self-managed files should not be checked
  "poetry.lock",    
]
per-file-ignores = [
  "tests/*.py: S101,D100,D101,D103,D104",  # tests without documentation, allow asserts
]
ignore = [
  "F401", "E501"  # pylint takes care of these
]
docstring-convention = "google"  # flake8-docstrings
docstring_style = "google"  # darglint

[tool.flakehell.plugins]
flake8-bandit = [
  "+*",
  "-S322",  # input for python2, no problem
]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-docstrings = [
  "+*",
  "-D202",  # black conflict
  "-D412",  # we do want lines between header and contents. See https://github.com/PyCQA/pydocstyle/issues/412
]
flake8-eradicate = ["+*"]
flake8-isort = ["+*"]
flake8-debugger = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
mccabe = ["+*"]
pep8-naming = [
  "+*",
  "-N805",  # pylint duplicate
]
pycodestyle = [
  "+*",
  "-E501"  # pylint duplicate
]
pyflakes = ["+*"]
pylint = ["+*"]
pandas-dev = ["+*"]

[tool.flakehell.exceptions."tests/"]
flake8-docstrings = [
  "-D100",
  "-D101",
  "-D102",
  "-D103",
  "-D104",
]
flake8-bandit = [
  "-S101",  # asserts are ok
]
flake8-darglint = [
  "-DAR101",
]
pylint = [
  "-C0115",
  "-C0115",
  "-C0116",
  "-C0116",
]
