[tool.flakehell]
format = "colored"
max_line_length = 79
exclude = [
  # self-managed files should not be checked
  "poetry.lock",
  "./.venv",
]
ignore = [
  "F401", "E501"  # pylint takes care of these
]
docstring-convention = "google"  # flake8-docstrings
docstring_style = "google"  # darglint

[tool.flakehell.plugins]
flake8-bandit = [
  "+*",
  "-S322",  # input for python2, no problem
  "-S404",  # control should be performed on subprocess usage, on import is useless
]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-docstrings = [
  "+*",
  "-D202",  # black conflict
  "-D412",  # we do want lines between header and contents. See https://github.com/PyCQA/pydocstyle/issues/412
]
flake8-eradicate = ["+*"]
flake8-debugger = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
mccabe = ["+*"]
pep8-naming = [
  "+*",
  "-N805",  # pylint duplicate
]
pycodestyle = [
  "+*",
  "-E501",  # pylint duplicate
  "-E203",  # false positives on list slice
  "-E722",  # bugbear duplicate
  "-E402",  # isort duplicate
]
pyflakes = ["+*"]
pylint = [
  "+*",
  "-E1136",  # disabled for python3.9, at least until support for 3.9 lands. See https://github.com/PyCQA/pylint/issues/3882
  "-C0114",  # flake8-docstrings duplicate
  "-W0611",  # pyflakes duplicate
]
pandas-dev = ["+*"]

[tool.flakehell.exceptions."docs/src/conf.py"]
flake8-eradicate = [
  "-E800",
]
flake8-docstrings = [
  "-D100",
  "-D101",
  "-D102",
  "-D103",
  "-D104",
]
flake8-builtins = [
  "-A001", # variable "copyright" is shadowing a python builtin -> sphinx wants it
]
pylint = [
  "-*",  # completely disable pylint for sphinx config
]
[tool.flakehell.exceptions."tests/"]
flake8-docstrings = [
  "-D100",
  "-D101",
  "-D102",
  "-D103",
  "-D104",
]
flake8-bandit = [
  "-S101",  # asserts are ok
]
flake8-darglint = [
  "-DAR101",
]
pylint = [
  "-C0415",
  "-C0115",
  "-C0115",
  "-C0116",
  "-C0116",
  "-R0201",
]
