[tool.poetry.dependencies]
importlib-metadata = {version = "^1.0", python = "<3.8", optional = true}

commitizen            = { version = "^2.14.2", optional = true }
pre-commit            = { version = "^2.10.1", optional = true }
drytoml            = { version = "^0.2.8", optional = true }

pytest                = { version = "^6.2.2", optional = true }
pytest-cov            = { version = "^2.11.1", optional = true }
pytest-html           = { version = "^3.1.1", optional = true }

Sphinx                = { version = "^3.4.3", optional = true }
sphinx-rtd-theme      = { version = "^0.5.1", optional = true }
m2r2                  = { version = "^0.2.7", optional = true }
recommonmark          = { version = "^0.7.1", optional = true }

# lint
flake8-bandit         = { version = "^2.1.2", optional = true }
flake8-bugbear        = { version = "^20.11.1", optional = true }
flake8-builtins       = { version = "^1.5.3", optional = true }
flake8-comprehensions = { version = "^3.3.1", optional = true }
darglint              = { version = "^1.6.0", optional = true }
flake8-docstrings     = { version = "^1.5.0", optional = true }
flake8-eradicate      = { version = "^1.0.0", optional = true }
flake8-mutable        = { version = "^1.2.0", optional = true }
flake8-debugger       = { version = "^4.0.0", optional = true }
flake8-pytest-style   = { version = "^1.3.0", optional = true }
pep8-naming           = { version = "^0.11.1", optional = true }
pylint                = { version = "^2.6.0", optional = true }

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.9.3"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.11.1"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.3.1"
flake8-docstrings = "^1.5.0"
flake8-eradicate = "^1.0.0"
flake8-debugger = "^4.0.0"
flake8-mutable = "^1.2.0"
black = "^20.8b1"
isort = "^5.7.0"
pylint = "^2.6.0"
flake8 = "^3.8.4"
mypy = "^0.790"
bandit = "^1.7.0"
coverage = "^5.3.1"
flake8-mypy = "^17.8.0"
pytest-cov = "^2.10.1"
docformatter-toml = "^0.1.0"
darglint = "^1.5.8"
flake8-pytest-style = "^1.3.0"
mccabe = "^0.6.1"
pep8-naming = "^0.11.1"
pycodestyle = "^2.6.0"
pyflakes = "^2.2.0"
pandas-vet = "^0.2.2"
Sphinx = "^3.4.3"
sphinx-rtd-theme = "^0.5.1"
m2r2 = "^0.2.7"
pytest-html = "^3.1.1"
importlib-metadata = {version = "^1.0", python = "<3.8"}
python-dotenv = "^0.15.0"
drytoml = {extras = ["black", "flakeheaven", "isort"], version = "^0.2.8"}
flakeheaven = "^0.10.0-alpha.0"
commitizen = "^2.14.2"
