name: "Check solved issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:

      # Runs a single command using the runners shell
      - name: Pandas vet - 106
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/deppen8/pandas-vet/issues/106 | grep state | grep open

      - name: Pandas vet - 108
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/deppen8/pandas-vet/issues/108 | grep state | grep open


      - name: Pylint - 3882
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/PyCQA/pylint/issues/3882 | grep state | grep open
